name: Vulnerability scan

on:
  release:
    types:
      - published
  schedule:
    - cron: "35 19 * * 6"
  workflow_dispatch:

jobs:
  project-scan:
    name: Scan the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          skip-dirs: ./integration/
          format: sarif
          output: trivy-results.sarif
          severity: "CRITICAL,HIGH"
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
